name: CI

on:
  push:
    branches:
      - main

  pull_request:

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        run: |
          npm install -g corepack@latest --force 
          corepack enable

      - uses: actions/setup-node@v6
        with:
          node-version: '24.18.0'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run test cases with coverage
        run: pnpm -r run test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          directory: ./packages/tskit/tests/coverage

  build:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        run: |
          npm install -g corepack@latest --force 
          corepack enable

      - uses: actions/setup-node@v6
        with:
          node-version: '24.18.0'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm -r run build

  typecheck:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        run: |
          npm install -g corepack@latest --force
          corepack enable

      - uses: actions/setup-node@v6
        with:
          node-version: '24.18.0'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm -r run typecheck

  lint:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        run: |
          npm install -g corepack@latest --force
          corepack enable

      - uses: actions/setup-node@v6
        with:
          node-version: '24.18.0'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint
